/**
 * Generated by scripts/generate-welcome-fox.ts — do not edit by hand.
 * Runtime rest-band data is self-contained and performs no asset I/O.
 */

/** Runtime rest-pose widths in columns. */
export const WELCOME_FOX_BAND_WIDTHS = [28, 36] as const

/** One runtime welcome-fox band width. */
export type WelcomeFoxBandWidth = (typeof WELCOME_FOX_BAND_WIDTHS)[number]

/** Fixed colors; index zero is transparent. */
export const WELCOME_FOX_PALETTE = [
  null,
  '#033257',
  '#2e8181',
  '#818296',
  '#c6976f',
  '#b99ca6',
  '#c4a7ab',
  '#d9bab3',
  '#eed1bf',
  '#f8cf9c',
  '#f8e0cb',
  '#fae5d0',
  '#fce9d3',
  '#fcead5',
  '#fcead5',
  '#fcebd7',
] as const

/** Palette-index rows for each runtime rest band. */
export const WELCOME_FOX_BANDS = {
  28: {
    width: 28,
    height: 30,
    rows: [
      '0000000000000000000000000000',
      '0000000000000000000088000000',
      '0000000000000000000c38000000',
      '000000000000000001dc57000000',
      '0000000000000000afd566000000',
      '0000000000000008dd2257000000',
      '0000000000f0101ddd8c5c000000',
      '00000000017dff7df3d23c000000',
      '000000011afddfddc6d761000000',
      '00001dddcdffddffda8281000000',
      '000ddddf8ddf4dddffd821000000',
      '01ddddffdddf94dffdf810000000',
      '0ffff882ddfd4dfbfddff2000000',
      '03553b7cffbdcdff11bf30000000',
      '0001855cdddaddf112dff1000000',
      '0000001f121addd26df700000000',
      '00000088d211fddcffa300010000',
      '0000008fafddf2dfd3500001a000',
      '0000000157adcfb38cc10001d100',
      '000000016da8768c8cd70007d870',
      '00000001ad8dc8fddd87000bddf0',
      '000000018fdadffdd828001ddff1',
      '000000003cffdfffd66801cfddf8',
      '00000001b3338dd8337678cffd87',
      '00000007f1a33c268518ddff2381',
      '0000000ad8df878df6cddf822861',
      '00000001882df1dd1cdf72222810',
      '00000000783a81887ddd62227600',
      '00000001fa178cff58a872785000',
      '0000000000023133113553100000',
    ],
  },
  36: {
    width: 36,
    height: 38,
    rows: [
      '000000000000000000000000000000000000',
      '0000000000000000000000002fa000000000',
      '000000000000000000000001dfa000000000',
      '00000000000000000000001cc37100000000',
      '0000000000000000000001dd356100000000',
      '000000000000000000001ddd365100000000',
      '00000000000000000001fdd2566100000000',
      '0000000000000100001cddd3b38100000000',
      '0000000000000a01018ddd5fc5c000000000',
      '0000000000011aff76dddf8d33c000000000',
      '000000000111ddddddffd2dc752000000000',
      '00000016df88fffdfdfff582252000000000',
      '00001addddddddffffffdfc35a1000000000',
      '0008dddddd8ffff84fffdffd580000000000',
      '018dfddfffddfdb94ffdffdd850000000000',
      '1ddffdffa2dddff44fffddfdfb8000000000',
      '153222237ddddffcdd8cdcd8ff1000000000',
      '018553776cfdc8dfddaf121df10000000000',
      '000118555cfffdaddf8116fdff1000000000',
      '000000006d31118dfd122fdd810000000000',
      '000000018fd1812ffdddddfa300001000000',
      '000000001cddffdf11dffc5100000f100000',
      '0000000012affffffddd678510000af30000',
      '0000000001133788a7378cac10000afd1100',
      '00000000016d8a88778cafdc700008df8f00',
      '0000000001c8d8cd8ccdfdfd100008dfdd10',
      '0000000007ccfcffddddf8d280002dddfd70',
      '00000000018d7dddfffdd5f310008fdfff70',
      '0000000000385fddffdcd51881acfffbdd70',
      '0000000001d73338ddb33737188ddfd2df80',
      '000000000ff88838887688388dfdf2623880',
      '000000000fdf6df7118dd5adddfd82288880',
      '0000000008db5dfd5adda7ddfdd222228810',
      '0000000001ab78df7cdd2dfdff22f4268500',
      '00000000005662dd8dfc5bd8822222571100',
      '0000000000ff828d8cf778dc822227881000',
      '00000000013df37bd7df5888863777510000',
      '000000000000001101110013331100000000',
    ],
  },
} as const

/** Canonical pose retained after attach. */
export const WELCOME_FOX_FINAL_FRAME = 'rest'
